# Generated by Django 5.2.13 on 2026-05-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='key',
            new_name='key_hash',
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(default='', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=10),
        ),
    ]
