# Generated by Django 5.2.13 on 2026-05-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_rename_key_apikey_key_hash_apikey_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
